### ISSUE TITLE
Does not work in Swift 4 + Storyboard

### ISSUE THREAD

**Issue by zenghaojim33** [listenzz/HBDNavigationBar#1]
This library works great in Swift 4 project but it doesn't  if I use storyboard ( as you did in your demo project) . Any idea how to fix that? Thanks!

**Comment by listenzz** [comment]
I guess you forgot to set the Navigation Bar class

![storyboard](https://user-images.githubusercontent.com/4386370/39051785-5cd44420-44dc-11e8-8126-0dfc9169889d.jpg)

**Comment by zenghaojim33** [comment]
Clean the project and it works. Starnge. But thanks for your remind!

发自我的 iPhone
