### ISSUE TITLE
设置translucent = true，怎么没起作用呢，视图原点还是导航栏左下

### ISSUE THREAD

**Issue by yangdehui** [listenzz/HBDNavigationBar#105]

**Comment by listenzz** [comment]
给个带透明的颜色就可以了

Listen

**Comment by yangdehui** [comment]
> 给个带透明的颜色就可以了 Listen
> […](#)
> 在 2019年12月13日，下午6:08，杨德辉 ***@***.***> 写道： ﻿ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yangdehui** [comment]
> 给个带透明的颜色就可以了 Listen
> […](#)
> 在 2019年12月13日，下午6:08，杨德辉 ***@***.***> 写道： ﻿ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您意思是给哪个属性设置，

**Comment by yangdehui** [comment]
> 给个带透明的颜色就可以了 Listen
> […](#)
> 在 2019年12月13日，下午6:08，杨德辉 ***@***.***> 写道： ﻿ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
    [self.navigationController.navigationBar setTranslucent:YES];
    self.navigationController.hbd_tintColor = RGBA_COLOR(99, 99, 99, 0.6);

    [self.navigationController.navigationBar setTranslucent:YES];
    self.navigationController.navigationBar.tintColor = RGBA_COLOR(99, 99, 99, 0.6);

    [self.navigationController.navigationBar setTranslucent:YES];
    self.hbd_barTintColor = RGBA_COLOR(99, 99, 99, 0.6);
这些对控制器view的原点都没有影响，在demo中测试直接用系统的设置有影响的
