### ISSUE TITLE
如何使用该库的分类属性全局的设置 UINavigationBar？

### ISSUE THREAD

**Issue by rakuyoMo** [listenzz/HBDNavigationBar#108]
文档里提到可以这么设置全局属性

```Objective-C
[[UINavigationBar appearance] setTintColor:UIColor.blackColor];
```

但是隐藏分割线的话：

```Swift
UINavigationBar.appearance().shadowImage = UIImage()
```

想恢复比较麻烦，而且不能用 `isBarShadowHidden` 恢复... 

设置隐藏，或其他属性的时候，的时候有办法全局设置吗？还是说只能在基类里进行配置？

**Comment by listenzz** [comment]
默认不隐藏，然后使用 `hbd_barShadowHidden`  控制

**Comment by rakuyoMo** [comment]
> 默认不隐藏，然后使用 `hbd_barShadowHidden` 控制

是默认不隐藏，但是这个属性是不是就不能配合 `appearance ` 全局设置了。只能写在基类里。

**Comment by listenzz** [comment]
shadowImage 是可以全局设置的
