### ISSUE TITLE
使用系统的UIImagePickerViewController想去改变导航栏的颜色

### ISSUE THREAD

**Issue by gongxinle** [listenzz/HBDNavigationBar#109]
当接入该库后，使用系统的相册，导航栏背景颜色怎么都改变不了

**Comment by listenzz** [comment]
本库没有使用 method swizzled， 所以对系统及第三方的导航栏不起作用，建议在启动 UI 前，通过 [UINavigationBar appearance] 来全局设置导航栏样式，不仅对本库生效，同时也对系统应用生效。

**Comment by gongxinle** [comment]
可是我单独去改变相册的导航栏为什么会不起作用呢，不管是在初始化控制器时改变还是在代理方法里改变都没有作用，感谢您的回复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: listenzz <notifications@github.com&gt;
发送时间: 2019年12月18日 11:12
收件人: listenzz/HBDNavigationBar <HBDNavigationBar@noreply.github.com&gt;
抄送: gongxinle <549036031@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[listenzz/HBDNavigationBar] 使用系统的UIImagePickerViewController想去改变导航栏的颜色 (#109)




本库没有使用 method swizzled， 所以对系统及第三方的导航栏不起作用，建议在启动 UI 前，通过 [UINavigationBar appearance] 来全局设置导航栏样式，不仅对本库生效，同时也对系统应用生效。

**Comment by gongxinle** [comment]
> 本库没有使用 method swizzled， 所以对系统及第三方的导航栏不起作用，建议在启动 UI 前，通过 [UINavigationBar appearance] 来全局设置导航栏样式，不仅对本库生效，同时也对系统应用生效。
