### ISSUE TITLE
在测试的时候，我Push一个storyboard的控制器，结果发现导航栏错位了，但是在载入完成的时候，又正常

### ISSUE THREAD

**Issue by jiyifanzi** [listenzz/HBDNavigationBar#12]
如题，Push的控制器，是这样初始化的[[UIStoryboard storyboardWithName:@"***" bundle:nil] instantiateViewControllerWithIdentifier:@"***"]

**Comment by listenzz** [comment]
请问这个控制器是否 UITableViewController. 
请尽量避免 UISrollView 及其子类作为 controller 的根 view

**Comment by listenzz** [comment]
我当时没能解决这个问题，而且很奇怪的是，只有启动后第一次 push 会这样，后续再 push 就不会了

**Comment by jiyifanzi** [comment]
嗯，我这边发现也是，第一次Push的时候，发现你的FakeBar的初始Origin 是0，0；第二次Push就正常了0，-64；应该和你的设置Translucent为YES有关，你手动计算frame得时候又用了convertRect这个。

我的解决方案：
在你HBDNavigationController.m里面
self.toFakeBar.subviews.lastObject.backgroundColor = to.hbd_computedBarTintColor;
这句代码下面

这个应该是你仿照系统写的一个fakeBar，你这里的frame，不能按照常规的来算，因为你的设置的了translucent，所以这里的frame的y应该固定从-64开始布局才对。

所以你在计算出他的frame的时候，应该不用系统返回的origin.y（系统多算了一个44，第二次push的时候是-108，正常应该是-44），直接把origin.y置为 -64，然后这个Bug就解决了，其他的情况我也测试了一下，没啥问题

**Comment by jiyifanzi** [comment]
刚刚这样解决的话，下面的shadow也需要重新计算一下

**Comment by jiyifanzi** [comment]
好像不对，这样的话，普通的Push也会被影响到，好像关键点就是看看这个视图的根视图是否是scrollerView

**Comment by jiyifanzi** [comment]
- (CGRect)fakeBarFrameForViewController:(UIViewController *)vc {
    UIView *back = self.navigationBar.subviews[0];
    CGRect frame = [self.navigationBar convertRect:back.frame toView:vc.view];
    frame.origin.x = vc.view.frame.origin.x;
    if ([vc.view isKindOfClass:[UIScrollView class]]) {
        frame.origin.y = -64;
    }else {
        
    }
    return frame;
}

改一下这个方法，就好了，判断一下。。。

**Comment by jiyifanzi** [comment]
恩恩，([UIScreen mainScreen].bounds.size.height == 812.0 ? 88 : 64)
我也测试了，没啥问题，刚刚想提交一个pull request的
