### ISSUE TITLE
关于导航栏返回/自定义UIBarButtonItem按钮侧滑消失过渡效果的优化

### ISSUE THREAD

**Issue by devcxm** [listenzz/HBDNavigationBar#120]
体验了京东的侧滑返回效果，相对于HBDNavigationBar，感觉京东返回按钮跟着当前页面移动消失体验更好，而HBDNavigationBar的返回按钮是慢慢变透明然后消失（系统风格），有时候会跟上一级页面出现重叠效果，有点突兀。不知道作者有没有办法实现这种过渡效果？附京东和HBDNavigationBar对比录屏。

[京东和HBDNavigationBar对比录屏](https://github.com/listenzz/HBDNavigationBar/files/4272830/AMOR6920.MP4.zip)

**Comment by listenzz** [comment]
@devcxm 京东这种方式，是把 UINavigationController 的 UINavigationBar 给隐藏了，然后给每个 UIViewController 添加一个 UINavigationBar，这种实现方式已经有人开源了。

**Comment by devcxm** [comment]
额，作者有没有知道的GitHub地址，去看看。
