### ISSUE TITLE
加入第三方相册选择组件问题

### ISSUE THREAD

**Issue by xmw-simon** [listenzz/HBDNavigationBar#136]
您好，我加入第三方相册组件的时候，一般第三方的相册会使用系统的UINavigationController。 然后就有问题了 选择完相册 或者取消，无论在哪个层级，都会返回到首页，而且底部tabBar还被重绘了，😂  请问有办法解决这个冲突么

**Comment by listenzz** [comment]
提供个 demo 吧

**Comment by xmw-simon** [comment]
我写了一个demo,但是又没有重现这个问题  我再检查一下是不是有冲突😂

**Comment by xmw-simon** [comment]
不是您这个组件的问题 打扰了
