### ISSUE TITLE
请问返回按钮上的标题，可以不显示吗？必须自定义返回按钮吗

### ISSUE THREAD

**Issue by iOSchuang** [listenzz/HBDNavigationBar#141]

**Comment by listenzz** [comment]
可以不显示，设置方法和使不使用本库无关。iOS 11 后可以通过 `[self.navigationItem setHidesBackButton:YES]` 来隐藏，也可以通过 runtime 来隐藏。

**Comment by iOSchuang** [comment]
非常感谢。但是这样设置是直接把返回按钮隐藏了，而想要的效果是二级页面的返回按钮，只显示返回箭头，不显示上一级级页面的标题

**Comment by listenzz** [comment]
@iOSchuang 不好意思哈，没留意。

使用 runtime 参考这篇文章 https://developer.aliyun.com/article/249374

或者使用基类，在 viewDidLoad 中设置 

```objc
self.navigationItem.backBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"" style:UIBarButtonItemStylePlain target:nil action:NULL];
```

**Comment by iOSchuang** [comment]
谢谢
