### ISSUE TITLE
有打算过swift化吗，能提供帮助

### ISSUE THREAD

**Issue by Girlsmile** [listenzz/HBDNavigationBar#155]

**Comment by listenzz** [comment]
无，因为本人不懂 swift, 也没有时间学习。swift 无法使用本库吗？

**Comment by l1Dan** [comment]
作者不好意思，借个楼哈。
@Girlsmile  祝你早日脱离 iOS 系统导航栏的坑 https://github.com/l1Dan/NXNavigationExtension.git
