### ISSUE TITLE
HBDNavigationBar 与 SegementSlide 同时使用会导致无法滑动返回

### ISSUE THREAD

**Issue by KennethLaw** [listenzz/HBDNavigationBar#156]
完整的Demo： https://github.com/KennethLaw/SegementSlide

初步调试了一下，问题出现在SegementSlideContentView中的UIScrollView，会导致handleNavigationTransition无法正常被调用。

参考资料：
1.  [多层 UIScrollView 嵌套滚动解决方案](https://juejin.cn/post/6844903776130695175)

**Comment by listenzz** [comment]
在 BaseNavigationController 加上这行代码

```objc
- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldBeRequiredToFailByGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer API_AVAILABLE(ios(7.0)){
    return YES;
}
```

我稍后发个版

**Comment by listenzz** [comment]
已发布 1.9.3

**Comment by KennethLaw** [comment]
Fixed
