### ISSUE TITLE
iOS15.2 Swift项目 自定义导航栏返回按钮图标无效

### ISSUE THREAD

**Issue by xygkevin** [listenzz/HBDNavigationBar#162]
iOS15.2系统，XSMax真机环境， Swift项目，导航栏继承自HBDNavigationController
1、修改导航栏返回按钮图标无效；
2、修改导航栏两侧按钮文字无效，A PUSH B后使用手势返回一点松手（仍停留在页面B）就生效了；

OC项目没有这个问题

**Comment by xygkevin** [comment]
纠正一下，OC项目也是上面两个问题

**Comment by listenzz** [comment]
问题 1 已验证，问题 2 请提供一个小 demo(OC)。

**Comment by listenzz** [comment]
问题 1 已修复
