### ISSUE TITLE
iOS16 运行Xcode提示 [<_UINavigationBarContentViewLayout valueForUndefinedKey:]

### ISSUE THREAD

**Issue by winterwd** [listenzz/HBDNavigationBar#174]
运行在iOS16上 提示:
[<_UINavigationBarContentViewLayout valueForUndefinedKey:]: this class is not key value coding-compliant for the key inlineTitleView.
![image](https://user-images.githubusercontent.com/14071671/192703748-acbba45e-3ef2-4c74-8221-68e91a0a9755.png)

**Comment by ElvistLui** [comment]
https://developer.apple.com/forums/thread/712240
用这里面的回答

**Comment by winterwd** [comment]
> 

已经用这个办法处理了，多谢
