### ISSUE TITLE
为什么不能设置导航栏背景图呢？

### ISSUE THREAD

**Issue by heyehao2008** [listenzz/HBDNavigationBar#2]
1、该库是让每个页面拥有了独立的navigationbar么？
2、为什么不支持设置导航栏背景图呢？这个需求还是蛮常见的

**Comment by listenzz** [comment]
1. 所有页面公用一个 navigationbar
2. 大多数情况下，导航栏都是纯色的背景，如果个别页面需要设置图片背景，可以设置 hbd_barAlpha 的值为 0， 然后在该页面相应的位置放置图片即可，看起来就像给该页面的 navigationbar 设置了背景图。
不支持导航栏背景图，主要还是因为作者还没遇到需要设置图片背景的需求，以及不希望辜负了那块毛玻璃。

**Comment by ShangZhengtao** [comment]
设置背景图片需求还是很常见呢。

**Comment by notePads** [comment]
希望加上

**Comment by sctengsen** [comment]
这个需求还是挺常见的,希望加上

**Comment by yiplee** [comment]
@listenzz  我能在这给我的 [YPNavigationBarTransition](https://github.com/yiplee/YPNavigationBarTransition) 打个广告吗？ 😂
支持背景图片哦！

**Comment by listenzz** [comment]
@yiplee 🤝

**Comment by listenzz** [comment]
@ALL 应诸位要求，已经实现此功能，使用方法及注意事项请看文档

**Comment by listenzz** [comment]
由于此问题已解决，关闭。
