### ISSUE TITLE
为什么要设置UIBarStyle 会导致状态栏不受VC控制

### ISSUE THREAD

**Issue by cherishloveyou** [listenzz/HBDNavigationBar#21]
不明白 这个导航栏为什么会动态设置BarStyle ,虽然通过设置bar的style也是会让导航栏的黑白变化 但是感觉这么做不符合逻辑

**Comment by listenzz** [comment]
当有导航栏时，状态栏受导航栏控制，不受 VC 控制。详情请参考[这篇文章](https://possiblemobile.com/2013/09/developers-guide-to-the-ios-7-status-bar/)

**Comment by cherishloveyou** [comment]
对的 经你提醒 是我记错了  因为这个状态栏问题 我一般是分类重写 UINavigationController  childViewControllerForStatusBarStyle childViewControllerForStatusBarHidden 让他返回topViewController的样式 返回viewContoller的样式   我一直记系统就是这样的
