### ISSUE TITLE
a bug

### ISSUE THREAD

**Issue by forkDog** [listenzz/HBDNavigationBar#22]
有一个需求是A跳转到B，B根据参数自动跳转到C，跳转到C完成后在B页面重新设置self.navigationController.viewControllers，
 [self.navigationController setViewControllers:viewCtrs animated:NO];
设置后相当于self.navigationController.viewControllers只剩下A和C，当我点击C返回按钮的时候，C导航栏标题消失了，返回到A界面（主页面是没有返回按钮的），会出现一个蓝色模糊的返回按钮

**Comment by listenzz** [comment]
请参考 [这里](https://github.com/listenzz/react-native-navigation-hybrid/blob/master/ios/NavigationHybrid/Controller/UINavigationController%2BHBD.m)
