### ISSUE TITLE
发现个小问题。

### ISSUE THREAD

**Issue by LouKit** [listenzz/HBDNavigationBar#26]
发现个问题，出现bug过程如下：
1.进首页AVC(导航栏隐藏)
 :push
2:BVC(有导航)
 :present 出一个新的带有导航的TestVC,且注册TestVC通知    

 UINavigationController *nav = [[UINavigationController alloc]initWithRootViewController: [TestVC new]];
    [self presentViewController:nav animated:YES completion:nil];

 3:TestVC 发出通知，且自身dismiss

 4:此时BVC接收到TestVC 发出的通知时，直接pop到根页面：[self.navigationController popToRootViewControllerAnimated:YES];

 5:这时页面应是到了AVC页面，但导航栏出现了。。。。

**Comment by listenzz** [comment]
我在 iOS 12 测试，按照你的描述回到首页，发现导航栏会出现一下然后消失。

不过为什么要在 dismiss 之前发通知呢，像下面这样就没有问题了

```objc
    [self dismissViewControllerAnimated:YES completion:^{
         [[NSNotificationCenter defaultCenter] postNotificationName:@"pop-to-root" object:nil];
    }];
```

**Comment by listenzz** [comment]
该 issue 已经修复，更新版本到 1.3.4 即可
