### ISSUE TITLE
push到下一页Bug

### ISSUE THREAD

**Issue by lztbwlkj** [listenzz/HBDNavigationBar#29]
最近更新到iOS 12后发现一个奇怪的问题：
![c0cbaba19c7c5b2b6dfdc7a371986979](https://user-images.githubusercontent.com/20568661/47332688-a70d7580-d6b2-11e8-8674-520158a4a430.png)
![2018-10-23 10 57 20](https://user-images.githubusercontent.com/20568661/47332691-a70d7580-d6b2-11e8-9818-a29c74abebac.png)
每次启动app,第一次push的时候都会出现，第二次就没有这个问题了，很奇怪，纠结了一天了.
我的代码是创建自定义的navigationController继承你的HBDNavigationController ，在这个自定义个nac中定制全局的nac样式和返回按钮

**Comment by listenzz** [comment]
出于什么考虑不用 `[UINavigationBar appearance]`  定制全局样式呢？

前后两个 controller 的导航栏颜色是否相同？

**Comment by lztbwlkj** [comment]
这是我的nac中的代码
+(void)initialize{
    [self setupNavigationBarTheme];
}

/**
 *  设置UIBarButtonItem的主题
 */
+ (void)setupNavigationBarTheme {
    UINavigationBar *navigationBar = [UINavigationBar appearance];
    [navigationBar setBarStyle:UIBarStyleDefault];
    [navigationBar setBarTintColor:[UIColor whiteColor]];
    [navigationBar setTintColor:[UIColor blackColor]];
    [navigationBar setShadowImage:[UIImage new]];
    
    if (![NSProcessInfo.processInfo isOperatingSystemAtLeastVersion:(NSOperatingSystemVersion){9,4,0}]) {
        // hide i px buttom line
        [navigationBar setBackgroundImage:[UIImage new]
                                                     forBarPosition:UIBarPositionAny
                                                         barMetrics:UIBarMetricsDefault];
    }
    
    navigationBar.translucent = NO;

    // 设置文字
    NSMutableDictionary *att = [NSMutableDictionary dictionary];
    att[NSFontAttributeName] = kPingFangRegular(19);
    att[NSForegroundColorAttributeName] = [UIColor blackColor];
    [[UINavigationBar appearance] setTitleTextAttributes:att];
}


- (void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated
{
    if (self.viewControllers.count > 0) {// 如果现在push的不是栈底控制器(最先push进来的那个控制器)
        viewController.hidesBottomBarWhenPushed = YES;
        UIBarButtonItem *negativeSpacer = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFixedSpace target:nil action:nil];
        negativeSpacer.width = -5;
        
        //设置导航栏的按钮
        UIBarButtonItem *backButton = [UIBarButtonItem itemWithImageName:@"navigation_backimage" highImageName:@"navigation_backimage" target:self action:@selector(backBtnClicked)];
        viewController.navigationItem.leftBarButtonItems = @[negativeSpacer, backButton];
        viewController.navigationItem.hidesBackButton = YES;
    }
    [super pushViewController:viewController animated:animated];
}

前一个页面title，为白色颜色透明，push到第二个界面title为黑色,背景白色

**Comment by listenzz** [comment]
设置 translucent 为 NO 是无效的。

有两个方向可以尝试下：

注释掉对 pushViewController 的重写

第二个页面有没有设置 edgesForExtendedLayout，如果有，去掉看看是否正常。

如果还没解决，稍后我有时间调试下。

**Comment by lztbwlkj** [comment]
edgesForExtendedLayout注释掉是可以了但导航栏挡住了我的部分view，这怎么解决

**Comment by listenzz** [comment]
@lztbwlkj 我会尽快处理此问题

**Comment by listenzz** [comment]
在你的 nav 中添加如下代码试试

```objc
- (void)viewWillLayoutSubviews {
    [super viewWillLayoutSubviews];
    // 修复一个神奇的 BUG
    self.topViewController.view.frame = self.topViewController.view.frame;
}
```

**Comment by listenzz** [comment]
@lztbwlkj 怎么样？要是可以的话我发个新版本了

**Comment by lztbwlkj** [comment]
你发布吧.我这里全部搞定了,昨天去掉edgesForExtendedLayout,适配了一下午。

**Comment by listenzz** [comment]
可以 checkout 到没适配前的代码，试试上述代码，我这边测试，你说的那个问题已经消失。

**Comment by lztbwlkj** [comment]
OK了，没问题了
