### ISSUE TITLE
iphone xr 未适配

### ISSUE THREAD

**Issue by nierongcheng** [listenzz/HBDNavigationBar#32]

**Comment by listenzz** [comment]
具体表现？

**Comment by BeingCode** [comment]
目前一个项目正在用，体验很好，说下遇到的问题
设置基类isTranslucent ＝NO，其中设置某一个界面hbd_barHidden ＝ YES(页面全屏显示)，从这个页面push出去，下个界面会下移，或者连续push然后返回，涉及到这样设置的都会有。

**Comment by nierongcheng** [comment]
![wx20181106-085243](https://user-images.githubusercontent.com/3412717/48036016-6416cc00-e1a1-11e8-8651-54bf8c8d3c77.png)
![iphonexs-xs-max-iphonexr-ui-design-4](https://user-images.githubusercontent.com/3412717/48036027-75f86f00-e1a1-11e8-9e07-8083757afc3b.jpg)

iPhone xr和xs max的高度是896

**Comment by listenzz** [comment]
感谢反馈，1.4.0 已经适配
