### ISSUE TITLE
如果上个导航栏有右按钮（rightBarButtonItem）的话，慢慢侧滑返回时有非常大的概率让右按钮颜色变淡。

### ISSUE THREAD

**Issue by ywdonga** [listenzz/HBDNavigationBar#35]
`
- (void)viewDidLoad {
    [super viewDidLoad];
    // Do any additional setup after loading the view.
    self.title = [NSString stringWithFormat:@"%lu", self.navigationController.childViewControllers.count];
    if (self.navigationController.childViewControllers.count <= 2) {
        self.title = @"我";
        // self.hbd_tintColor = UIColor.whiteColor;
    } else {
        self.title = @"收藏";
        self.hbd_tintColor = UIColor.blueColor;
        // self.hbd_barTintColor = UIColor.redColor;
        // self.hbd_barStyle = UIBarStyleBlack;
        // self.hbd_titleTextAttributes = @{ NSForegroundColorAttributeName: UIColor.whiteColor };
    }
    self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:@"test" style:(UIBarButtonItemStylePlain) target:self action:@selector(pushToNext:)];
}
`
我在这个页面加了个 test按钮，然后push到下个界面，慢慢侧滑返回就有很大概率出现这个问题，手机系统11.4.1

**Comment by listenzz** [comment]
松开手后会变回正常颜色么？

**Comment by ywdonga** [comment]
不会，如果触发了的话就永远是暗色了。

**Comment by listenzz** [comment]
OK, 我复现了

**Comment by ywdonga** [comment]
侧滑时要很慢很慢，然后在超过屏幕的一半的某一位置松手，反复尝试 应该很容易复现

**Comment by ywdonga** [comment]
哈哈，好吧，那就没办法了
