### ISSUE TITLE
我在代码中使用HBDNavigationController，会导致内存泄露

### ISSUE THREAD

**Issue by wuhongxing** [listenzz/HBDNavigationBar#38]
我封装的控制器可能比较复杂，所以产生了内存泄露，我换成简单一点的Controller或者把你的HBDNavigationController换成系统的UINavigationController都不会导致内存泄露！

**Comment by listenzz** [comment]
你使用的是 1.4.4 版本吗？把 HBDNavigationController 中的 poppingViewController 换成 weak 试试

```objc
@property (nonatomic, weak) UIViewController *poppingViewController;
```

**Comment by wuhongxing** [comment]
我刚刚试了一下，目前还没有发现其他问题，谢谢啦！

**Comment by listenzz** [comment]
@wuhongxing 是说问题解决了吗？

**Comment by wuhongxing** [comment]
现在不会产生内存泄露了，但是切换页面时，上面的 navigationBar 变得非常混乱！

**Comment by listenzz** [comment]
怎么个混乱发呢？

**Comment by wuhongxing** [comment]
万分抱歉，这个页面的 navigatoincontroller.delegate 被更改了，所以导致 HBDNavigationController.navigationController.delegate 代理方法不执行

**Comment by listenzz** [comment]
@wuhongxing 你找到了原因就好
