### ISSUE TITLE
设置页面hbd_barHidden = YES页面push的问题

### ISSUE THREAD

**Issue by lztbwlkj** [listenzz/HBDNavigationBar#43]
第一个页面全屏显示设置hbd_barHidden = true，将要消失的时候hbd_barHidden = false，然后push到下一个页面导航栏会出现白条闪一下，之后就正常了,每次push都会这样，下面是源码
[Swift-12Day.zip](https://github.com/listenzz/HBDNavigationBar/files/2661967/Swift-12Day.zip)

**Comment by listenzz** [comment]
为什么将要消失的时候设置 hbd_barHidden = false 呢？不是很明白

**Comment by lztbwlkj** [comment]
😂😂这不是push到下一页显示导航栏嘛！难道我的代码写错了？

**Comment by listenzz** [comment]
下一页是由下一页控制的，跟上一页无关。声明式 API。

**Comment by listenzz** [comment]
你下一页什么也不需要做。

**Comment by listenzz** [comment]
在 viewDidLoad 声明这一页需要什么效果就可以了，不会影响下一页的。

**Comment by lztbwlkj** [comment]
知道了   感谢🙏
