### ISSUE TITLE
圣诞快乐~~~有个需求:全屏返回手势,部分页面禁止

### ISSUE THREAD

**Issue by greezi** [listenzz/HBDNavigationBar#46]
首先祝各位圣诞快乐,🎅Merry Christmas 🎄
其次才是需求,哈哈哈~~~

**Comment by listenzz** [comment]
不打算支持全屏返回手势，侧滑返回是系统默认的交互方式，也是用户熟悉的交互方式。建议怼产品经理或自行修改源码。[图解实现UINavigation的全屏右滑功能
](https://www.jianshu.com/p/006370e7fe67)

**Comment by listenzz** [comment]
可以和 [FDFullscreenPopGesture](https://github.com/forkingdog/FDFullscreenPopGesture) 一起使用，详见 [README](https://github.com/listenzz/HBDNavigationBar/blob/master/README.md) 文档
