### ISSUE TITLE
关于隐藏导航栏的问题

### ISSUE THREAD

**Issue by jiejianyou** [listenzz/HBDNavigationBar#47]
我隐藏了导航栏 ，标题和左边的按钮都隐藏了  就是右边的不隐藏
![2019-01-05 2 02 06](https://user-images.githubusercontent.com/19336708/50721051-78b90700-10f3-11e9-9589-6eb85bdc8ad1.png)
![2019-01-05 2 03 51](https://user-images.githubusercontent.com/19336708/50721054-81114200-10f3-11e9-99e3-5098e70f104b.png)

![2019-01-05 2 15 17](https://user-images.githubusercontent.com/19336708/50721100-a2266280-10f4-11e9-8d79-e557ecbf4b08.png)

**Comment by jiejianyou** [comment]
> 我隐藏了导航栏 ，标题和左边的按钮都隐藏了 就是右边的不隐藏
> ![2019-01-05 2 02 06](https://user-images.githubusercontent.com/19336708/50721051-78b90700-10f3-11e9-9589-6eb85bdc8ad1.png)
> ![2019-01-05 2 03 17](https://user-images.githubusercontent.com/19336708/50721053-7e165180-10f3-11e9-81a8-c7d5cb80207a.png)
> ![2019-01-05 2 03 51](https://user-images.githubusercontent.com/19336708/50721054-81114200-10f3-11e9-99e3-5098e70f104b.png)

**Comment by listenzz** [comment]
是的，刚看了下源码，右边按钮不会隐藏。

因为在隐藏导航栏时，需要隐藏返回按钮，所以顺带隐藏了左边的按钮。

但是右边按钮没做任何处理，因为没想到在需要隐藏导航栏时，还会去设置右边的按钮。

**Comment by jiejianyou** [comment]
我这边有个需求  下拉刷新的时候  需要隐藏导航栏

**Comment by listenzz** [comment]
好的，你可以重写 setHbd_barHidden 这个方法，在里面处理。

```objc
- (void)setHbd_barHidden:(BOOL)hidden {
    [super setHbd_barHidden:(BOOL)hidden];
    if (hidden) {
        self.navigationItem.leftBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:[UIView new]];
        self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:[UIView new]];
        self.navigationItem.titleView = [UIView new];
    } else {
        self.navigationItem.leftBarButtonItem = ...
        self.navigationItem.rightBarButtonItem = ...
    }
```
