### ISSUE TITLE
导航栏总是透明的，设置hbd_barAlpha也没用

### ISSUE THREAD

**Issue by 809532119** [listenzz/HBDNavigationBar#49]
我的导航控制器没有使用StoryBoard，用代码写的，然后继承自HBDNavigationController
然后每个viewController的导航栏都是透明的，设置hbd_barAlpha也不起作用，这个怎么解决？折腾好久了。

**Comment by 809532119** [comment]
-(void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated {
    if (self.viewControllers.count > 0) {
        viewController.hidesBottomBarWhenPushed = YES;
    }
    viewController.hbd_barImage = [UIImage new];
    viewController.hbd_barTintColor = [UIColor whiteColor];
    viewController.hbd_barShadowHidden = YES;
    viewController.hbd_titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor blackColor],NSFontAttributeName : [UIFont boldSystemFontOfSize:18]};
    [self updateNavigationBarAlphaForViewController:viewController];
    [super pushViewController:viewController animated:YES];
}
就重写了这个方法

**Comment by listenzz** [comment]
你好，删掉

```
viewController.hbd_barImage = [UIImage new];
[self updateNavigationBarAlphaForViewController:viewController];
```

另外，推荐在  AppDelegate 中进行 UINavigationBar 的配置

```objc
@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {

   [[UINavigationBar appearance] setBarTintColor:[UIColor whiteColor]];
   [[UINavigationBar appearance] setTitleTextAttributes: ...];
}
@end
```

**Comment by 809532119** [comment]
谢谢，我试试

**Comment by 809532119** [comment]
您好，按照您说的删掉了那两行后，还是不行，导航栏依旧是透明的

**Comment by listenzz** [comment]
想要全局隐藏阴影，像下面这样设置即可

```objc
[[UINavigationBar appearance] setShadowImage:[UIImage new]];
```

**Comment by 809532119** [comment]
我看您的Demo上很正常啊，可以通过设置hbd_barAlpha自由的控制导航栏的透明度，为什么我运用到我的项目中就是这样的问题？

**Comment by 809532119** [comment]
好的，我试试

**Comment by 809532119** [comment]
> 那就把下面的都删了
> 
> ```
> viewController.hbd_barImage = [UIImage new];
> viewController.hbd_barTintColor = [UIColor whiteColor];
> viewController.hbd_barShadowHidden = YES;
> viewController.hbd_titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor blackColor],NSFontAttributeName : [UIFont boldSystemFontOfSize:18]};
> [self updateNavigationBarAlphaForViewController:viewController];
> ```
> 在 AppDelegate 中设置
> 
> ```objc
> [[UINavigationBar appearance] setBarTintColor:[UIColor whiteColor]];
> [[UINavigationBar appearance] setShadowImage:[UIImage new]];
> [[UINavigationBar appearance] setTitleTextAttributes: @{NSForegroundColorAttributeName : [UIColor blackColor],NSFontAttributeName : [UIFont boldSystemFontOfSize:18]}];
> ```

还是不行，导航栏还是透明的

**Comment by listenzz** [comment]
发个 demo 给我看看？

**Comment by 809532119** [comment]
> 发个 demo 给我看看？

好

**Comment by 809532119** [comment]
[Uploading Test.zip…]()

**Comment by 809532119** [comment]
> 发个 demo 给我看看？

发到您的邮箱了

**Comment by listenzz** [comment]
因为背景是白的，导航栏也设置成白的了，所以看起来就像是透明的。

按照下面的去做，换个颜色试试，记得把 ViewController.m 中的颜色也换掉。

> 那就把下面的都删了
> 
> ```
> viewController.hbd_barImage = [UIImage new];
> viewController.hbd_barTintColor = [UIColor whiteColor];
> viewController.hbd_barShadowHidden = YES;
> viewController.hbd_titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor blackColor],NSFontAttributeName : [UIFont boldSystemFontOfSize:18]};
> [self updateNavigationBarAlphaForViewController:viewController];
> ```
> 在 AppDelegate 中设置
> 
> ```objc
> [[UINavigationBar appearance] setBarTintColor:[UIColor whiteColor]];
> [[UINavigationBar appearance] setShadowImage:[UIImage new]];
> [[UINavigationBar appearance] setTitleTextAttributes: @{NSForegroundColorAttributeName : [UIColor blackColor],NSFontAttributeName : [UIFont boldSystemFontOfSize:18]}];
> ```

**Comment by 809532119** [comment]
> 因为背景是白的，导航栏也设置成白的了，所以看起来就像是透明的。
> 
> 按照下面的去做，换个颜色试试，记得把 ViewController.m 中的颜色也换掉。
> 
> > 那就把下面的都删了
> > ```
> > viewController.hbd_barImage = [UIImage new];
> > viewController.hbd_barTintColor = [UIColor whiteColor];
> > viewController.hbd_barShadowHidden = YES;
> > viewController.hbd_titleTextAttributes = @{NSForegroundColorAttributeName : [UIColor blackColor],NSFontAttributeName : [UIFont boldSystemFontOfSize:18]};
> > [self updateNavigationBarAlphaForViewController:viewController];
> > ```
> > 在 AppDelegate 中设置
> > ```objc
> > [[UINavigationBar appearance] setBarTintColor:[UIColor whiteColor]];
> > [[UINavigationBar appearance] setShadowImage:[UIImage new]];
> > [[UINavigationBar appearance] setTitleTextAttributes: @{NSForegroundColorAttributeName : [UIColor blackColor],NSFontAttributeName : [UIFont boldSystemFontOfSize:18]}];
> > ```

好的

**Comment by harveyseeking** [comment]
楼主透明问题解决了吗
