### ISSUE TITLE
微信的那个效果不是用的iOS自带edge swipe dismiss么？

### ISSUE THREAD

**Issue by atom2ueki** [listenzz/HBDNavigationBar#5]
想讨论一下，如题，如果想改变swipe的范围，swizzle一下那个method也可以办到

**Comment by listenzz** [comment]
我不太理解，swizzle 是最后的手段，一般不会轻易使用，比较推荐使用子类

**Comment by listenzz** [comment]
由于很久没有响应，因此关闭

**Comment by atom2ueki** [comment]
@listenzz swizzle的方式确实只能做到vc dismiss，不能做到push，因为只是replace了vc自带的`UIScreenEdgePanGestureRecognizer`的方式
Reference: https://github.com/forkingdog/FDFullscreenPopGesture
