### ISSUE TITLE
三个页面，移除中间一个页面后返回，第一个页面的nav样式变成了被移除的那个页面的

### ISSUE THREAD

**Issue by Fzzzzzzzz** [listenzz/HBDNavigationBar#50]
A、B、C三个页面，A->B->C,然后在C出来后，通过setControllers去掉中间的B后，再返回到A。这个时候，A页面上的item跟title变成了已去除的B页面的配置。

**Comment by lifeMiik** [comment]
试试
 [vc didMoveToParentViewController:nil];
 [vc.view removeFromSuperview];
行不行

**Comment by listenzz** [comment]
这不是本库的问题，建议参考其它资料解决。
