### ISSUE TITLE
侧滑返回过程中,能设置两个导航栏之间不存在渐变效果吗?

### ISSUE THREAD

**Issue by DogTwoChen** [listenzz/HBDNavigationBar#52]
![91548734086_ pic](https://user-images.githubusercontent.com/18676761/51883155-bb9d9000-23bc-11e9-83fc-e1b389019441.jpg)

**Comment by listenzz** [comment]
什么意思呢？不是很明白哦

**Comment by DogTwoChen** [comment]
就是去除侧滑返回的过程中,当前页的tabbar上的按钮文字渐变成上一页的按钮文字的效果,而是两个nav互不想干
