### ISSUE TITLE
反馈一个问题。pop回前一个页面，前一个页面导航栏回先透明再恢复

### ISSUE THREAD

**Issue by LiYang-Young** [listenzz/HBDNavigationBar#54]
我从A控制器push到B控制器，其中B控制器中有一句代码：self.navigationController.delegate = self;然后从Bpop回A，A页面导航栏回先透明。去掉那句代码就可以了。不知道这种问题该怎么解决？是产生冲突了吗？

**Comment by LiYang-Young** [comment]
说错了，是A控制器有一句代码：self.navigationController.delegate = self;然后B控制器导航栏隐藏self.hbd_barHidden = YES;。A控制器导航栏显示。然后从Bpop回A，A页面导航栏会先透明

**Comment by listenzz** [comment]
是冲突了，因为 self.navigationController.delegate = self

**Comment by LiYang-Young** [comment]
我还遇到一个冲突，现象是一样的，但是具体因为什么，目前还不知道。对于这种问题，请问该怎么解决？目前来看，感觉会冲突的地方还是挺多的。。

**Comment by listenzz** [comment]
本库内部设置了 delegate，一旦改写，就会发生冲突。请问你改写 navigationController 的 delegate 是要实现什么功能呢

**Comment by LiYang-Young** [comment]
navigationController 的 delegate这个，目前没实现什么功能，所以我删掉了，冲突解决了。然后我用了一个第三方，WMPageController，用了里面的一个控制器WMStickyPageController，然后这个问题就又出现了。

**Comment by listenzz** [comment]
#76
