### ISSUE TITLE
导航栏颜色问题

### ISSUE THREAD

**Issue by BeingCode** [listenzz/HBDNavigationBar#55]
如图，点击键盘上按钮使光标上移或下移
![50951551084415_ pic_hd](https://user-images.githubusercontent.com/44461496/53325135-846bc180-391d-11e9-994b-c6241156f79f.jpg)
![50961551084454_ pic_hd](https://user-images.githubusercontent.com/44461496/53325139-8766b200-391d-11e9-9dfe-dde898913d6c.jpg)

**Comment by listenzz** [comment]
ViewController 的根 view 是 ScrollView?

**Comment by BeingCode** [comment]
这是一个tableview分组

**Comment by BeingCode** [comment]
完整界面是这个样子￼￼￼￼
![51081551145362_ pic_hd](https://user-images.githubusercontent.com/44461496/53381174-e0c8f280-39aa-11e9-96e8-992fedb4eff4.jpg)

**Comment by listenzz** [comment]
使用了 UITableViewController?

**Comment by BeingCode** [comment]
没有，直接tableview

**Comment by BeingCode** [comment]
只要不点击上移下移就不会有问题
![51111551146464_ pic](https://user-images.githubusercontent.com/44461496/53381939-71a0cd80-39ad-11e9-9a0c-b8d26a0e35c1.jpg)

**Comment by listenzz** [comment]
TableView 作为 ViewController 的根 view ？

**Comment by BeingCode** [comment]
方便加我一下QQ:1323637096我把代码发你一下

**Comment by listenzz** [comment]
这个问题我解决了没
