### ISSUE TITLE
侧滑返回失效，求解决

### ISSUE THREAD

**Issue by harveyseeking** [listenzz/HBDNavigationBar#57]
侧滑返回失效，求解决

**Comment by harveyseeking** [comment]
是应为内部页面设置过self.navigationController.interactivePopGestureRecognizer吗，一级页面没有设置过

**Comment by listenzz** [comment]
@harveyseeking `self.navigationController.interactivePopGestureRecognizer` 被覆盖了就会出问题

**Comment by harveyseeking** [comment]
我的导航栏继承自UINavigationController侧滑就没问题，继承HBDNavigationController就不能用手势侧滑，是忘了设置哪个属性么

**Comment by listenzz** [comment]
可能是 navigationController.delegate 被覆盖了

**Comment by harveyseeking** [comment]
所有vigationController.delegate 和navigationController.interactivePopGestureRecognizer相关的都删除了，直接显示两个空白页面做跳转也是一样的，HBDNavigationController *baseNavc = [[HBDNavigationController alloc]initWithRootViewController:childVC];一使用就侧滑失效，

**Comment by listenzz** [comment]
有使用 method swizzle 来改变 interactivePopGestureRecognizer 和 delegate 吗？

**Comment by harveyseeking** [comment]
没有，很奇怪，同样的写法，我新建的demo就没问题，自己的项目就失效了

**Comment by harveyseeking** [comment]
对了pod只能搜到1.4.5,搜不到1.5.0

-> HBDNavigationBar (1.4.5)
   An aspiring UINavigationBar.
   pod 'HBDNavigationBar', '~> 1.4.5'
   - Homepage: https://github.com/listenzz/HBDNavigationBar
   - Source:   https://github.com/listenzz/HBDNavigationBar.git
   - Versions: 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.5, 1.3.4, 1.3.3,
   1.3.2, 1.3.1, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.0, 1.0.1, 1.0.0 [master repo]

**Comment by listenzz** [comment]
> 对了pod只能搜到1.4.5,搜不到1.5.0
> 
> -> HBDNavigationBar (1.4.5)
> An aspiring UINavigationBar.
> pod 'HBDNavigationBar', '~> 1.4.5'
> 
> * Homepage: https://github.com/listenzz/HBDNavigationBar
> * Source:   https://github.com/listenzz/HBDNavigationBar.git
> * Versions: 1.4.5, 1.4.4, 1.4.3, 1.4.2, 1.4.1, 1.4.0, 1.3.5, 1.3.4, 1.3.3,
>   1.3.2, 1.3.1, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.0, 1.0.1, 1.0.0 [master repo]

#17

**Comment by harveyseeking** [comment]
你好大神，侧滑失效的问题还是没解决，我把我的代码发给你，有时间帮我看一下可以吗

**Comment by listenzz** [comment]
OK，作为附件发送到我邮箱 listenzz@163.com

**Comment by harveyseeking** [comment]
好的发过去了，好像是和pod的其他库有关系，当我把其他库全部删除时侧滑就可以用了

**Comment by listenzz** [comment]
你用的是 Xcode 9 ?

**Comment by harveyseeking** [comment]
xcode10，需要手动添加libc++9

**Comment by harveyseeking** [comment]
找到原因了，是因为这个库YHPopupView

**Comment by listenzz** [comment]
是的，我也刚找到，一个个 pod 试下来就可以了

**Comment by harveyseeking** [comment]
谢谢大神，辛苦了

**Comment by harveyseeking** [comment]
对了如果用hbd_backInteractive自定义了返回事件，侧滑好像有点问题，页面滑动速度比手指滑动速度要快

**Comment by listenzz** [comment]
`UIViewController+YYPopupViewController` 这个分类也实现了 UIGestureRecognizerDelegate，和本库发生冲突，因为本库也实现了 UIGestureRecognizerDelegate。

我已经修改了本库的实现方式，以便使它们可以兼容。
