### ISSUE TITLE
[self.navigationBar setTranslucent:false]没有效果

### ISSUE THREAD

**Issue by harveyseeking** [listenzz/HBDNavigationBar#58]
在哪设置Translucent都没有效果

**Comment by listenzz** [comment]
是的，无效。详见文档。

**Comment by harveyseeking** [comment]
我想要设置页面导航栏纯白色无阴影，但是需要导航栏底部分割线，请问需要怎么做呢

**Comment by listenzz** [comment]
全局设置，对所有控制器生效

```objc
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
    [[UINavigationBar appearance] setBarTintColor:UIColor.whiteColor];
}
```

局部设置，对具体某个控制器生效

```objc
- (void)viewDidLoad {
    [super viewDidLoad];
    self.hbd_barTintColor = UIColor.whiteColor
}
```

**Comment by harveyseeking** [comment]
好的谢谢

**Comment by listenzz** [comment]
如果需要权设置分割线颜色
使用 `[[UINavigationBar appearance] setShadowImage:xxx]`

**Comment by harveyseeking** [comment]
我如下重写本导航栏，隐藏tabbar生效，修改返回文字却没有效果
- (void)pushViewController:(UIViewController *)viewController animated:(BOOL)animated {
    UIBarButtonItem *backItem = [[UIBarButtonItem alloc]initWithTitle:@"返回" style:UIBarButtonItemStylePlain target:self action:nil];
    viewController.navigationItem.backBarButtonItem = backItem;

    if (self.viewControllers.count != 0) {
        viewController.hidesBottomBarWhenPushed = YES;
    }

    [super pushViewController:viewController animated:animated];
}

**Comment by harveyseeking** [comment]
要怎么修改返回按钮文字呢

**Comment by listenzz** [comment]
@harveyseeking  假如从 A push 到 B，设置 A 的 backBarButtonItem，那么在 B 的导航栏就能看到 A 设置的效果。

可以使用 method swizzle。
