### ISSUE TITLE
返回按钮无法隐藏的问题 && present一个SDK中封装好的页面如何隐藏导航栏？

### ISSUE THREAD

**Issue by xiaoning1009** [listenzz/HBDNavigationBar#59]
QA1 : A页面Push到B页面，在B页面中设置self.hbd_barHidden = YES,导航栏可以隐藏，但是返回按钮还在，而且禁用backInteractive和swip都失效，仍旧可以滑动返回或者点击返回按钮返回
QA2：调起SDK中某个页面，该页面有present方法提供，发现无法隐藏导航栏

**Comment by listenzz** [comment]
QA1: 返回按钮是使用 leftBarButtonItem 实现的？有无覆盖 navigationController.interactivePopGestureRecognizer.delegate ?
QA2: 如果 SDK 提供的不是一个 UINavigationController ， 取得该控制器实例后，设置它的 hbd_barHidden 为 YES，把该控制器包裹在 HBDNavigationController 中，再 present。
