### ISSUE TITLE
navigationbar   系统的是设置一种颜色就不会改变，你这个框架没有一个默认的颜色，或者跟系统一样的吗？

### ISSUE THREAD

**Issue by fei1234** [listenzz/HBDNavigationBar#6]

**Comment by listenzz** [comment]
可以通过 appearance 设置默认颜色，如果不设置，会根据 barStyle 计算默认颜色，效果和系统默认一样

Listen

**Comment by fei1234** [comment]
hbd_barTintColor  这个参数不设置，navigationbar的背景颜色，不会跟上一层vc一样，不是和系统一样的
