### ISSUE TITLE
导航栏问题（push新界面，返回后就下移）

### ISSUE THREAD

**Issue by BeingCode** [listenzz/HBDNavigationBar#61]
![1051552026154_ pic_hd](https://user-images.githubusercontent.com/44461496/54011596-083f6c80-41ae-11e9-9514-181ecffab6f8.jpg)
![1061552026172_ pic_hd](https://user-images.githubusercontent.com/44461496/54011597-09709980-41ae-11e9-9c0c-11f22a0a32b8.jpg)

**Comment by listenzz** [comment]
这个页面的 root view 是 UIScrollView 或其子类？

**Comment by BeingCode** [comment]
对，但是必须要用，有没有解决办法

**Comment by listenzz** [comment]
@BeingCode 没有办法把该 root view 放在一个普通的 view 里面吗？

**Comment by BeingCode** [comment]
我是控制器上加的scrollview
 [self.view addSubview:self.mxScrollView];

**Comment by BeingCode** [comment]
你意思是再嵌套一层view吗

**Comment by listenzz** [comment]
@BeingCode 不是

**Comment by listenzz** [comment]
方便提供一个可以复现此问题的 demo?

**Comment by BeingCode** [comment]
好

**Comment by BeingCode** [comment]
我把demo给你
[Uploading Test.zip…]()

**Comment by BeingCode** [comment]
我怎么发给你

**Comment by BeingCode** [comment]
QQ可以吧

**Comment by listenzz** [comment]
作为附件，发送到 listenzz@163.com

**Comment by BeingCode** [comment]
可以，麻烦帮忙解决一下，3q

**Comment by BeingCode** [comment]
已经发给你了

**Comment by listenzz** [comment]
@BeingCode 已收到

**Comment by BeingCode** [comment]
能解决吗

**Comment by listenzz** [comment]
正在看，会有办法解决的。

**Comment by BeingCode** [comment]
好的，3q

**Comment by listenzz** [comment]
主要原因是该页面的 frame 被改动了，被改动原因不明。可以通过在该页面添加如下代码修复：

```objc
- (void)viewWillLayoutSubviews {
    self.view.frame = self.navigationController.view.bounds;
    [super viewWillLayoutSubviews];
}
```

**Comment by BeingCode** [comment]
我现在用的就是这个方法，还是用了这个框架的原因，正常没有这个问题

**Comment by listenzz** [comment]
我找个时间检查下，非常感谢你的 demo

**Comment by BeingCode** [comment]
3q

**Comment by listenzz** [comment]
经过我的调试，找到原因了，NinaPagerView 这个库里面有一行代码

<img width="1113" alt="屏幕快照 2019-03-14 下午8 07 44" src="https://user-images.githubusercontent.com/4386370/54355746-db4ef600-4694-11e9-9f4c-1cbda0326a4f.png">

就是 161 那行代码，注释掉就好了，暂时不知这行代码对该库有什么用。

这行代码会导致控制器的 view 位于导航栏的下面（below）而不是底下(under)

**Comment by TimorYang** [comment]
@BeingCode NinaPageView 这个库我个人是不建议使用的，使用确实很便捷，但是这个库做了过多的处理，导致遇到问题时，会耗费更多的时间。
