### ISSUE TITLE
pop手势在UIPageViewController里失效

### ISSUE THREAD

**Issue by internalG** [listenzz/HBDNavigationBar#64]
把下面3行去掉就好了，请问gesture必须重载吗？
`
- (void)viewDidLoad {
    [super viewDidLoad];
//    self.gestureRecognizerDelegate = [[HBDGestureRecognizerDelegate alloc] initWithNavigationController:self];
//    self.interactivePopGestureRecognizer.delegate = self.gestureRecognizerDelegate;
//    [self.interactivePopGestureRecognizer addTarget:self action:@selector(handlePopGesture:)];
    self.delegate = self;
    [self.navigationBar setTranslucent:YES];
    [self.navigationBar setShadowImage:[UINavigationBar appearance].shadowImage];
}
`

**Comment by listenzz** [comment]
去掉会导致 hbd_backInteractive 这个属性失效，如果不使用该属性，去掉无妨。
还会影响通过侧滑返回时，返回按钮的过渡效果，也可以不用太在意。

**Comment by internalG** [comment]
谢谢。如果需要在某个controller里用xib实现定制的navigationbar应该怎么做呢？
