### ISSUE TITLE
这个pop回来导航栏是什么问题

### ISSUE THREAD

**Issue by forkdog** [listenzz/HBDNavigationBar#66]
![Untitled](https://user-images.githubusercontent.com/16552858/57180125-309acd00-6eb8-11e9-8838-34f9e4aa4696.gif)

**Comment by listenzz** [comment]
重现步骤？

**Comment by forkdog** [comment]
就是从首页push过去测试页，首页导航栏是深色的，测试页是白色的，然后pop返回，首页导航栏有一个往下移动的过程，这个是什么问题

**Comment by listenzz** [comment]
能提供个 demo 吗，我这边无法重现
