### ISSUE TITLE
设置hbd_barStyle标题栏颜色问题

### ISSUE THREAD

**Issue by pinksunHenry** [listenzz/HBDNavigationBar#69]
首先，这个开源库解决了我大部分需要的问题。但是不知道是使用问题，还是什么，当我的自控制器设置为hbd_barStyle = UIBarStyleBlack，导航栏颜色标题色为白色，但是当我通过手势返回开始的时候，导航标题变为上一个控制器的标题颜色。然后在返回手势取消的时候，不能显示当前控制器正确的标题颜色。能否帮忙分析一下，该问题可能的原因。

**Comment by listenzz** [comment]
请提供一个能复现问题的 demo

**Comment by pinksunHenry** [comment]
后面解决了，好像是因为同时使用了QMUI这个库，里面的QMUINavigationButton这个类，其中方法替换影响的。
navigationBar:shouldPopItem:
替换为
navigationButton_navigationBar:shouldPopItem:
引起的，大神有空可以考虑一下这种情况的处理
