### ISSUE TITLE
透明的时候遇到问题

### ISSUE THREAD

**Issue by miku1958** [listenzz/HBDNavigationBar#7]
公司的旧项目,有一个遗留 bug需要设置控制器
	self.extendedLayoutIncludesOpaqueBars = YES;
才能实现 self.view穿过 navigationbar

但设置了
	extendedLayoutIncludesOpaqueBars = YES 
	self.hbd_barHidden = YES;
后 navigationbar 就会变成黑色的,在 view hierarchy中看到_UIBarBackground和_UIVisualEffectBackdropView都是黑色的

请问怎么解决

**Comment by miku1958** [comment]
其他同事找到原因了,有个地方用非常微妙的写法设置了 navigationbar的translucent为  NO....

建议设置self.hbd_barHidden = YES;的时候把navigationbar的translucent为YES吧

**Comment by listenzz** [comment]
你好， navigationbar的translucent 在 HBDNavigationController 的 viewDidLoad 中已经设置为 YES。我会想办法禁止将 translucent 设置为 NO。感谢你的反馈。
