### ISSUE TITLE
你好，如果视图作为抽屉视图的中间控制器，设置hbd_barStyle无效,我用的viewDock

### ISSUE THREAD

**Issue by H2OB** [listenzz/HBDNavigationBar#72]

**Comment by listenzz** [comment]
你好，我自己也写了个抽屉，使用起来表现正常：

https://github.com/listenzz/react-native-navigation-hybrid/blob/master/ios/NavigationHybrid/ViewController/HBDDrawerController.m

**Comment by H2OB** [comment]
@listenzz 感谢作者，抽屉控制器里少了两行代码
- (UIViewController *)childViewControllerForStatusBarStyle {
    return self.centerViewController;
}

- (UIViewController *)childViewControllerForStatusBarHidden {
    return self.centerViewController;
}
