### ISSUE TITLE
加入转场动画导航栏设置失效的问题（具体操作如描述）

### ISSUE THREAD

**Issue by BeingCode** [listenzz/HBDNavigationBar#78]
引导页后（点立即进入）加入转场动画，导航栏就变白色了（设置不起作用）
[UIView transitionWithView:[UIApplication sharedApplication].keyWindow
                      duration:0.75f
                       options:UIViewAnimationOptionTransitionFlipFromLeft
                    animations:^{
                        
                        [UIApplication sharedApplication].keyWindow.rootViewController = self.rootVC;
                    }
                    completion:nil];
直接：[UIApplication sharedApplication].keyWindow.rootViewController = self.rootVC没任何问题

**Comment by listenzz** [comment]
我们使用以下方式转场，没发现异常

```objc
UIWindow *mainWindow = [self mainWindow];
    [UIView transitionWithView:mainWindow duration:0.15f options:UIViewAnimationOptionTransitionCrossDissolve animations:^{
        BOOL oldState = [UIView areAnimationsEnabled];
        [UIView setAnimationsEnabled:NO];
        mainWindow.rootViewController = rootViewController;
        mainWindow.windowLevel = UIWindowLevelNormal;
        if (!mainWindow.isKeyWindow) {
            [mainWindow makeKeyAndVisible];
        }
        [UIView setAnimationsEnabled:oldState];
    } completion:^(BOOL finished) {
        
    }];
```
