### ISSUE TITLE
setBarTintColor crash

### ISSUE THREAD

**Issue by CHPisces** [listenzz/HBDNavigationBar#8]
HBDNavigationBar setBarTintColor方法中，subviews[1]导致的越界crash
![image](https://user-images.githubusercontent.com/16495807/39683186-bb26fc2c-51e6-11e8-959f-3a8249ac58a7.png)
![image](https://user-images.githubusercontent.com/16495807/39683193-c73f2962-51e6-11e8-84ff-f638f448ca19.png)

**Comment by listenzz** [comment]
请升级到 1.2.1

请问操作系统版本是不是 10.3.1 ？

**Comment by CHPisces** [comment]
我这边没有复现，友盟上全部出现在9.3.5上面，fabric上9.3.5、9.1.0、8.1.2、8.4.1上面都有。

**Comment by CHPisces** [comment]
因为这个错误太严重了，只能暂时移除掉HBD了，因为我这边测试时无法复现，所以就算更新版本也是有些担忧。

**Comment by CHPisces** [comment]
好的，谢谢，后续关注。

**Comment by CHPisces** [comment]
我看到1.2.1版本中使用lastObject已经修复了。针对之前的版本(1.1.0)，我提供一个线索，没有ipad真机，在模拟器上运行了一下，发现在ipad 2(9.3),ipad retina(9.0、9.3)上都是必现的。

**Comment by listenzz** [comment]
@CHPisces 已发邮件

**Comment by zhao651** [comment]
你好，为什么静态库找不到呢？是要自己封装？

**Comment by listenzz** [comment]
@zhao651 你把 HBDNavigationBar/Classes 下那三个类拷贝到自己的项目中就可以了

**Comment by zhao651** [comment]
> ld: library not found for -lHBDNavigationBar
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
    表示还是不行，已经把你说的那个拷贝到项目中了。按照网上找的方法，删除-L（Library search path） 里面所有的路径。都没有用，还是报上面的错误。

**Comment by zhao651** [comment]
才入手IOS，想学习学习一些不错的界面效果，结果大部分时候就卡在这个发布配置这里。很无赖。

**Comment by listenzz** [comment]
@zhao651 建议你了解下 cocoapods

**Comment by zhao651** [comment]
谢谢
