### ISSUE TITLE
崩溃

### ISSUE THREAD

**Issue by domanc** [listenzz/HBDNavigationBar#82]
在其他页面push没问题，不知道为什么push其中一个会崩溃在

 self.topViewController.view.frame = self.topViewController.view.frame; 在这段代码上

**Comment by listenzz** [comment]
self.topViewController.view 会调用 controller 的 loadView 和 viewDidLoad 方法

**Comment by domanc** [comment]
> self.topViewController.view 会调用 controller 的 loadView 和 viewDidLoad 方法

嗯，谢谢，我发现问题了，只要我是用xib约束自定view，赋值给tableHeaderView就会崩溃.请问怎么解决，只能用纯代码吗？

**Comment by listenzz** [comment]
在 1.6.7 版本
下面这段奇葩的代码已经移除

```objc
self.topViewController.view.frame = self.topViewController.view.frame
```
