### ISSUE TITLE
希望可以添加测滑返回拦截

### ISSUE THREAD

**Issue by lztbwlkj** [listenzz/HBDNavigationBar#84]
在某些编辑界面需要手动返回提示”是否保存本次编辑“，希望可以支持一下

**Comment by listenzz** [comment]
重写当前 ViewController 的 `hbd_backInteractive` 或 `hbd_swipeBackEnabled` ，返回 `NO` 即可

**Comment by lztbwlkj** [comment]
这个不是关闭当前页面的的测滑返回了吗？

**Comment by listenzz** [comment]
hbd_backInteractive 可以兼顾测滑和点击返回按钮的情况。重写该方法，如果需要提示是否保存，就弹出提示，返回 NO。

**Comment by lztbwlkj** [comment]
hbd_backInteractive可以拦截测滑返回，但返回按钮我自己通过self.navigationItem.leftBarButtonItem全局添加的 拦截不到了
