### ISSUE TITLE
请问不需要适配iOS13吗？

### ISSUE THREAD

**Issue by LiYang-Young** [listenzz/HBDNavigationBar#91]
升级iOS13之后，sdk出现很多莫名奇妙的问题。

**Comment by listenzz** [comment]
使用最新的 1.6.6 版本，不需要做任何改动

 #85

**Comment by LiYang-Young** [comment]
我是刚更新的，更新完发现去掉了几个方法，然后就改了一下。运行后确实遇到几个问题。方便留个联系方式交流一下吗？录屏您看一下，谢谢

**Comment by listenzz** [comment]
![WechatIMG2](https://user-images.githubusercontent.com/4386370/66697275-a7a97c80-ed06-11e9-87a6-0806b4a3692a.jpg)
